"""'initial'

Revision ID: 6164f7dbb329
Revises: 
Create Date: 2022-07-05 22:22:52.223059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6164f7dbb329'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peoples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.String(length=15), nullable=True),
    sa.Column('eye_color', sa.String(length=15), nullable=True),
    sa.Column('films', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('hair_color', sa.String(length=30), nullable=True),
    sa.Column('height', sa.String(length=5), nullable=True),
    sa.Column('homeworld', sa.String(length=50), nullable=True),
    sa.Column('mass', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('skin_color', sa.String(length=30), nullable=True),
    sa.Column('species', sa.String(length=200), nullable=True),
    sa.Column('starships', sa.String(length=200), nullable=True),
    sa.Column('vehicles', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peoples_name'), 'peoples', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peoples_name'), table_name='peoples')
    op.drop_table('peoples')
    # ### end Alembic commands ###
